from email.message import EmailMessage
import ssl
import smtplib

email_sender = 'xx@gmail.com'
password = ''
email_reciever = 'tempmail'


subject = 'Automated email from python script'
body = """
Hii, This email is autogenerated using python script for learning how to send email in python
"""
em = EmailMessage()
em["From"] = email_sender
em["To"] = email_reciever
em["Subject"] = subject
em.set_content(body)

context = ssl.create_default_context()
with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as server:
    server.login(email_sender, password)
    server.sendmail(email_sender, email_reciever, em.as_string())
